<?
$recipient = "$yourname <$email>";
$subject = "New User Details";
$message .= "Hello $yourname,\n\n";
$message .= "You have been added as a user to our site.\n";
$message .= "This email contains your username and password to login:\n\n";
$message .= "Username - $username1\n";
$message .= "Password - $pass\n\n\n";
$message .= "Please do not respond to this message as it is automatically generated and is for information purposes only\n\n";
$message .= "This is an automated message generated by the IFS system.\n";
$message .= "IFS originally created for use by Obsidian Fleet, http://www.obsidianfleet.net, but now licensed under the GNU GPL.\n";
$message .= "See http://www.obsidianfleet.net/ifs/ for details on how to obtain this software.\n";
$headers .= "From: " . emailfrom . "\n";
$headers .= "X-Sender:<" . webmasteremail . "> \n";
$headers .= "X-Mailer: PHP\n"; // mailer
$headers .= "Return-Path: <$email>\n";  // Return path for errors
mail($recipient, $subject, $message, $headers);
?>