<?php
/***
  * INTEGRATED FLEET MANAGEMENT SYSTEM
  * OBSIDIAN FLEET
  * http://www.obsidianfleet.net/ifs/
  *
  * Developer:	Frank Anon
  * 	    	fanon@obsidianfleet.net
  *
  * Version:	1.11
  * Release Date: June 3, 2004
  *
  * Copyright (C) 2003-2004 Frank Anon for Obsidian Fleet RPG
  * Distributed under the terms of the GNU General Public License
  * See doc/LICENSE for details
  *
  * Date:	12/13/03
  * Comments: Footer included on every page
  *
 ***/

if (!$no_back_to)
{
	?>
	<br /><br />
	<center><a href="<? echo $relpath ?>index.php">Back to main page</a></center>
	<?php
}

if ( $pop == "y" && defined("JS") )
	echo "<center><a href=\"javascript:window.close();\">Close This Window</a></center>";

?>

<br /><br />

<table width="80%" border="0" cellspacing="2" cellpadding="2" align="center">
	<tr>
		<td class="small">
			<div align="center" class="smallgrey">IFS software - All Rights Reserved Obsidian Fleet RPG &#169; 2001 - 2003.</div>
			<?php
            if ($pop != "y")
            {
            	?>
				<div align="center" class="smallgrey"><br /><br />
	            This page generated by the IFS system.<br />
	            IFS originally created by Frank Anon for use in Obsidian Fleet, http://www.obsidianfleet.net.<br />
	            See http://www.obsidianfleet.net/ifs/ for details on how to obtain this software.<br />
				<?php
	            //  End TIMER
				GLOBAL $stimer;
				list ($etimer1, $etimer2) = explode (" ", microtime ());
				$etimer = (float)$etimer1 + (float)$etimer2;
				echo "Page Rendered in: <b>" . round($etimer - $stimer, 3) . "</b> seconds.";
    	        ?>
                </div>
			</td>
			<td rowspan="2">
				<a href="http://www.obsidianfleet.net/ifs/"><img src="images/ifs.gif" border="0" alt="Powered by Obsidian Fleet IFS" /></a>
			</td>
		</tr>

		<tr>
			<td valign="bottom">
				<div align="center">
                <?php
                if ($poweredby)
                {
					echo "<a href=\"http://www.mamboserver.com\" target=\"_blank\">";
		            echo "<img src=\"{$relpath}{$poweredby}\" width=\"278\" height=\"9\" alt=\"Powered by Mambo Site Server\" border=\"0\" />";
					echo "</a>\n\n";
                }
                echo "</div>\n";
            }
            ?>
		</td>
	</tr>
</table>

</body>
</html>

<?php
ob_end_flush();
?>